# Generated by Django 4.1b1 on 2022-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=90, null=True)),
                ("url", models.URLField(unique=True, verbose_name="url")),
                (
                    "description",
                    models.TextField(blank=True, max_length=400, null=True),
                ),
            ],
        ),
    ]
