# Generated by Django 4.1b1 on 2022-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
