# Generated by Django 4.1b1 on 2022-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="TITLE")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="one word for title alias",
                        unique=True,
                        verbose_name="SLUG",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="simple description text",
                        max_length=140,
                        verbose_name="DESCRIPTION",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATED"),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="MODIFIED"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "my_post",
                "ordering": ("-modified_date",),
            },
        ),
    ]
