# Generated by Django 4.1b1 on 2022-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="author of the content",
                max_length=50,
                verbose_name="AUTHOR",
            ),
        ),
    ]
